name: CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  BuildNuget:
    name: Build & Publish Nuget Packages
    runs-on: windows-latest
    environment: 
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Add NuGet Private Source
        run: dotnet nuget add source --username diversiwaver --password "${{secrets.NUGET_ACCESS_TOKEN}}" --store-password-in-clear-text --name githubNuget "https://nuget.pkg.github.com/diversiwaver/index.json"
      - name: Build & Publish Nuget Packages
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser publish --github-token "${{secrets.GITHUB_TOKEN}}" --nuget-token "${{secrets.NUGET_TOKEN}}" src/dotnet-releaser-release.toml
